### ISSUE TITLE
Building for PowerPC (ppc/e500mc)

### ISSUE THREAD

**Issue by DannyBoyKN** [siemens/embb#110]
For your news articale appeared on 12 of May 2017, "Improved Platform Support using C11/C++11-based Atomic Operations"

> EMB² ships with implementations of atomic operations for x86 and ARM processors to be usable with older compilers (supporting C99 / C++03 only). This is important for applications that cannot be migrated easily to more recent language standards. Thanks to Sebastian Huber from embedded brains GmbH, EMB² can now be built using atomic operations provided by C11 / C++11. Just add the option -DUSE_C11_AND_CXX11=ON when generating native build files, e.g. type cmake .. -DUSE_C11_AND_CXX11=ON. This way, EMB² can be used on a variety of platforms besides x86 and ARM such as PowerPC, MIPS, or SPARC. Thanks a lot for the great work and contributing to EMB²!

I just wondering if this works and just naively tried to build but got lots of errors as:
```
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:65:2: error: #error "unsupported platform"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:475:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/load.h:107:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:476:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
multicore/embb/base_c/include/embb/base/c/internal/atomic/and_assign.h:124:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:477:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from multicore/embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/store.h:103:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:478:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/or_assign.h:109:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:479:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/xor_assign.h:110:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:480:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/swap.h:111:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:481:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/fetch_and_add.h:114:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:482:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/compare_and_swap.h:123:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_init_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:756:3: warning: implicit declaration of function 'embb_internal__atomic_store_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_init_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:775:3: warning: implicit declaration of function 'embb_internal__atomic_store_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_init_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:813:3: warning: implicit declaration of function 'embb_internal__atomic_store_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_and_assign_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1022:3: warning: implicit declaration of function 'embb_internal__atomic_and_assign_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_and_assign_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1042:3: warning: implicit declaration of function 'embb_internal__atomic_and_assign_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_and_assign_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1082:3: warning: implicit declaration of function 'embb_internal__atomic_and_assign_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_compare_and_swap_char':
multicore/embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1303:3: warning: implicit declaration of function 'embb_internal__atomic_compare_and_swap_1' [-Wimplicit-function-declaration]
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_compare_and_swap_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1325:3: warning: implicit declaration of function 'embb_internal__atomic_compare_and_swap_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_compare_and_swap_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1369:3: warning: implicit declaration of function 'embb_internal__atomic_compare_and_swap_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_fetch_and_add_char':
multicore/embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1610:3: warning: implicit declaration of function 'embb_internal__atomic_fetch_and_add_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_fetch_and_add_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1633:3: warning: implicit declaration of function 'embb_internal__atomic_fetch_and_add_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_fetch_and_add_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1679:3: warning: implicit declaration of function 'embb_internal__atomic_fetch_and_add_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_load_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1929:3: warning: implicit declaration of function 'embb_internal__atomic_load_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_load_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1949:3: warning: implicit declaration of function 'embb_internal__atomic_load_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_load_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1989:3: warning: implicit declaration of function 'embb_internal__atomic_load_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_or_assign_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2212:3: warning: implicit declaration of function 'embb_internal__atomic_or_assign_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_or_assign_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2232:3: warning: implicit declaration of function 'embb_internal__atomic_or_assign_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_or_assign_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2272:3: warning: implicit declaration of function 'embb_internal__atomic_or_assign_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_swap_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2772:3: warning: implicit declaration of function 'embb_internal__atomic_swap_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_swap_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2795:3: warning: implicit declaration of function 'embb_internal__atomic_swap_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_swap_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2841:3: warning: implicit declaration of function 'embb_internal__atomic_swap_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_xor_assign_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:3094:3: warning: implicit declaration of function 'embb_internal__atomic_xor_assign_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_xor_assign_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:3114:3: warning: implicit declaration of function 'embb_internal__atomic_xor_assign_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_xor_assign_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:3154:3: warning: implicit declaration of function 'embb_internal__atomic_xor_assign_4' [-Wimplicit-function-declaration]
gmake[2]: *** [base_c/CMakeFiles/embb_base_c.dir/src/internal/thread_index.c.o] Error 1

```

**Comment by tobias-schuele** [comment]
As for issue #109, the output of cmake and the build process (with VERBOSE=1) would be very useful.
Thanks

**Comment by marcus-winter** [comment]
I suspect you tried to build without C(++)11 support first and reconfigured afterwards. Did you clear the cache inbetween? This is necessary to reconfigure the cmake_config.h files.

**Comment by DannyBoyKN** [comment]
What you mean by '_Did you clear the cache inbetween?_'
I did '`rm -rf *`' in the build folder and
```
cmake -DUSE_C11_AND_CXX11=ON ..
cmake --build .

```
but the errors are the same!
CMakeCache.txt, CMakeFiles/CMakeError.log, CMakeFiles/CMakeOutput.log and base_c/include/embb/base/c/internal/atomic/atomic_sizes.h are attached as well.
[cmake.tar.gz](https://github.com/siemens/embb/files/1379109/cmake.tar.gz)
[atomic_sizes.h.txt](https://github.com/siemens/embb/files/1379102/atomic_sizes.h.txt)
[CMakeCache.txt](https://github.com/siemens/embb/files/1379103/CMakeCache.txt)
[CMakeOutput.log](https://github.com/siemens/embb/files/1379104/CMakeOutput.log)
[CMakeError.log](https://github.com/siemens/embb/files/1379111/CMakeError.log)

Do you think this is related to #109 although the platforms are different ?
```
$ make VERBOSE=1
/usr/bin/cmake -Hembb -Bembb/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start embb/build/CMakeFiles embb/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `embb/build'
make -f partest_build/CMakeFiles/partest.dir/build.make partest_build/CMakeFiles/partest.dir/depend
make[2]: Entering directory `embb/build'
cd embb/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" embb embb/build/partest embb/build embb/build/partest_build embb/build/partest_build/CMakeFiles/partest.dir/DependInfo.cmake --color=
make[2]: Leaving directory `embb/build'
make -f partest_build/CMakeFiles/partest.dir/build.make partest_build/CMakeFiles/partest.dir/build
make[2]: Entering directory `embb/build'
make[2]: Nothing to be done for `partest_build/CMakeFiles/partest.dir/build'.
make[2]: Leaving directory `embb/build'
/usr/bin/cmake -E cmake_progress_report embb/build/CMakeFiles  91 92 93 94 95 96 97 98 99
[  9%] Built target partest
make -f partest_build/CMakeFiles/partest_test.dir/build.make partest_build/CMakeFiles/partest_test.dir/depend
make[2]: Entering directory `embb/build'
cd embb/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" embb embb/build/partest embb/build embb/build/partest_build embb/build/partest_build/CMakeFiles/partest_test.dir/DependInfo.cmake --color=
make[2]: Leaving directory `embb/build'
make -f partest_build/CMakeFiles/partest_test.dir/build.make partest_build/CMakeFiles/partest_test.dir/build
make[2]: Entering directory `embb/build'
make[2]: Nothing to be done for `partest_build/CMakeFiles/partest_test.dir/build'.
make[2]: Leaving directory `embb/build'
/usr/bin/cmake -E cmake_progress_report embb/build/CMakeFiles  100
[ 10%] Built target partest_test
make -f base_c/CMakeFiles/embb_base_c.dir/build.make base_c/CMakeFiles/embb_base_c.dir/depend
make[2]: Entering directory `embb/build'
cd embb/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" embb embb/base_c embb/build embb/build/base_c embb/build/base_c/CMakeFiles/embb_base_c.dir/DependInfo.cmake --color=
make[2]: Leaving directory `embb/build'
make -f base_c/CMakeFiles/embb_base_c.dir/build.make base_c/CMakeFiles/embb_base_c.dir/build
make[2]: Entering directory `embb/build'
/usr/bin/cmake -E cmake_progress_report embb/build/CMakeFiles 11
[ 11%] Building C object base_c/CMakeFiles/embb_base_c.dir/src/internal/thread_index.c.o
cd embb/build/base_c && /usr/bin/cc  -D_GNU_SOURCE -pthread -std=c11 -Wall -Wextra -O3 -DNDEBUG -DNDEBUG -Iembb/base_c/include -Iembb/build/base_c/include -Iembb/base_c/test -Iembb/build/base_c/../partest/include    -o CMakeFiles/embb_base_c.dir/src/internal/thread_index.c.o   -c embb/base_c/src/internal/thread_index.c
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:65:2: error: #error "unsupported platform"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:475:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/load.h:107:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:476:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/and_assign.h:124:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:477:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/store.h:103:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:478:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/or_assign.h:109:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:479:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/xor_assign.h:110:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:480:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/swap.h:111:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:481:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/fetch_and_add.h:114:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/internal/atomic/atomic.h:482:0,
                 from embb/base_c/include/embb/base/c/atomic.h:360,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/compare_and_swap.h:123:2: error: #error "Unknown architecture"
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_init_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:756:3: warning: implicit declaration of function 'embb_internal__atomic_store_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_init_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:775:3: warning: implicit declaration of function 'embb_internal__atomic_store_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_init_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:813:3: warning: implicit declaration of function 'embb_internal__atomic_store_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_and_assign_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1022:3: warning: implicit declaration of function 'embb_internal__atomic_and_assign_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_and_assign_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1042:3: warning: implicit declaration of function 'embb_internal__atomic_and_assign_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_and_assign_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1082:3: warning: implicit declaration of function 'embb_internal__atomic_and_assign_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_compare_and_swap_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1303:3: warning: implicit declaration of function 'embb_internal__atomic_compare_and_swap_1' [-Wimplicit-function-declaration]
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_compare_and_swap_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1325:3: warning: implicit declaration of function 'embb_internal__atomic_compare_and_swap_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_compare_and_swap_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1369:3: warning: implicit declaration of function 'embb_internal__atomic_compare_and_swap_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_fetch_and_add_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1610:3: warning: implicit declaration of function 'embb_internal__atomic_fetch_and_add_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_fetch_and_add_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1633:3: warning: implicit declaration of function 'embb_internal__atomic_fetch_and_add_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_fetch_and_add_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1679:3: warning: implicit declaration of function 'embb_internal__atomic_fetch_and_add_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_load_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1929:3: warning: implicit declaration of function 'embb_internal__atomic_load_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_load_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1949:3: warning: implicit declaration of function 'embb_internal__atomic_load_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_load_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:1989:3: warning: implicit declaration of function 'embb_internal__atomic_load_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_or_assign_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2212:3: warning: implicit declaration of function 'embb_internal__atomic_or_assign_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_or_assign_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2232:3: warning: implicit declaration of function 'embb_internal__atomic_or_assign_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_or_assign_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2272:3: warning: implicit declaration of function 'embb_internal__atomic_or_assign_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_swap_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2772:3: warning: implicit declaration of function 'embb_internal__atomic_swap_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_swap_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2795:3: warning: implicit declaration of function 'embb_internal__atomic_swap_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_swap_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:2841:3: warning: implicit declaration of function 'embb_internal__atomic_swap_4' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_xor_assign_char':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:3094:3: warning: implicit declaration of function 'embb_internal__atomic_xor_assign_1' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_xor_assign_short':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:3114:3: warning: implicit declaration of function 'embb_internal__atomic_xor_assign_2' [-Wimplicit-function-declaration]
embb/base_c/include/embb/base/c/internal/atomic/atomic.h: In function 'embb_atomic_xor_assign_int':
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:3154:3: warning: implicit declaration of function 'embb_internal__atomic_xor_assign_4' [-Wimplicit-function-declaration]
make[2]: *** [base_c/CMakeFiles/embb_base_c.dir/src/internal/thread_index.c.o] Error 1
make[2]: Leaving directory `embb/build'
make[1]: *** [base_c/CMakeFiles/embb_base_c.dir/all] Error 2
make[1]: Leaving directory `embb/build'
make: *** [all] Error 2

```

**Comment by DannyBoyKN** [comment]
Since this version of embb was copied from that one described as the cause of #110, I re-copied the newly cloned embb from that x86 machine (no direct internet connection) again.

I did rebuild everything again:
```
cd build
rm -rf *
cmake -DUSE_C11_AND_CXX11=ON ..
cmake --build .

```
and got a different error:
```
...
Scanning dependencies of target embb_base_c
[ 11%] Building C object base_c/CMakeFiles/embb_base_c.dir/src/time.c.o
[ 12%] Building C object base_c/CMakeFiles/embb_base_c.dir/src/internal/thread_index.c.o
In file included from embb/base_c/include/embb/base/c/atomic.h:360:0,
                 from embb/base_c/src/internal/thread_index.c:29:
embb/base_c/include/embb/base/c/internal/atomic/atomic.h:45:23: fatal error: stdatomic.h: No such file or directory
compilation terminated.
gmake[2]: *** [base_c/CMakeFiles/embb_base_c.dir/src/internal/thread_index.c.o] Error 1
gmake[1]: *** [base_c/CMakeFiles/embb_base_c.dir/all] Error 2
gmake: *** [all] Error 2

```

**Comment by tobias-schuele** [comment]
Which version of GCC are you using on PowerPC? Looks like it doesn't support C11 atomics.

**Comment by DannyBoyKN** [comment]
It is gcc 4.7.3. Indeed, it seems as if doesn't support C11 atomics.
However, I did the build on a standard x86 64bit Ubuntu 16.04.3 LTS with different gcc compiler versions: 6.x, 5.x, 4.8.x and 4.7.4
And each of them worked.
However, I did not set the cmake flag `USE_C11_AND_CXX11=ON`.
I'm going to try to get/build the gcc 4.9.2 to work on my ppc-e500mc ...

**Comment by tobias-schuele** [comment]
>It is gcc 4.7.3. Indeed, it seems as if doesn't support C11 atomics.
Yes, see https://gcc.gnu.org/wiki/C11Status (5th row containing stdatomic.h).

>However, I did the build on a standard x86 64bit Ubuntu 16.04.3 LTS with different gcc compiler versions: 6.x, 5.x, 4.8.x and 4.7.4
If C/C++11 is disabled, which is the default, EMBB compiles with older versions of GCC such as 4.7 oder 4.8 (but only ARM and x86)

>I'm going to try to get/build the gcc 4.9.2 to work on my ppc-e500mc ...
Unfortunately, there is currently no way around (except for porting the native EMBB atomics to PowerPC, which is feasible but requires some effort).

**Comment by DannyBoyKN** [comment]
I managed to compile gcc 4.9.2 for p4080 target. With `export PATH=/home/$USER/gcc-4.9.2/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin` was not sufficient for building, but had to use:

`cmake .. -DUSE_C11_AND_CXX11=ON -DCMAKE_CXX_COMPILER=/home/$USER/gcc-4.9.2/bin/g++ -DCMAKE_C_COMPILER=/home/$USER/gcc-4.9.2/bin/gcc
`

However the ./binaries/run_tests.sh failed on one module:
(with `export LD_LIBRARY_PATH=/home/$USER/gcc-4.9.2/lib/`)
```
...
Running NetworkSocketTest ...
CHECK FAILED
Expression: err != 0
File      : /home/vitasuser/multicore/embb/mtapi_plugins_c/mtapi_network_c/test/embb_mtapi_network_test_socket.cc
Method    : void NetworkSocketTest::TestBasic()
Line      : 62

Test unit: mtapi network socket test
Method thread num: 0
Method iteration num: 0
--------------------------------------------------------------------------------
CHECK FAILED
Expression: err == -1
File      : /home/vitasuser/multicore/embb/mtapi_plugins_c/mtapi_network_c/test/embb_mtapi_network_test_socket.cc
Method    : void NetworkSocketTest::TestBasic()
Line      : 65

Test unit: mtapi network socket test
Method thread num: 0
Method iteration num: 0
--------------------------------------------------------------------------------
CHECK FAILED
Expression: err != 0
File      : /home/vitasuser/multicore/embb/mtapi_plugins_c/mtapi_network_c/test/embb_mtapi_network_test_socket.cc
Method    : void NetworkSocketTest::TestBasic()
Line      : 70

Test unit: mtapi network socket test
Method thread num: 0
Method iteration num: 0
--------------------------------------------------------------------------------
CHECK FAILED
Expression: err != 0
File      : /home/vitasuser/multicore/embb/mtapi_plugins_c/mtapi_network_c/test/embb_mtapi_network_test_socket.cc
Method    : void NetworkSocketTest::TestBasic()
Line      : 76

Test unit: mtapi network socket test
Method thread num: 0
Method iteration num: 0

```

> ... except for porting the native EMBB atomics to PowerPC, which is feasible but requires some effort

Would it be possible to point me to the relevant parts for such an adaptation ?

**Comment by tobias-schuele** [comment]
Apparently, there is a problem with setting up network sockets on your machine. However, you can safely ignore the failed checks unless you want to use the network plugin. This plugin is only necessary if you want to connect multiple machines, but not for single multicore systems. We'll have a look at the respective source code lines to get an idea of what's going wrong.

>Would it be possible to point me to the relevant parts for such an adaptation ?

You can find the implementations of the native EMB² atomics in the directory `embb/base_c/include/embb/base/c/internal/atomic`. For each operation such as load, store, compare-and-swap, etc. there is one file containing the code for the different platforms. The actual implementation is selected using ifdefs, e.g.:

```
#ifdef EMBB_PLATFORM_ARCH_X86
...
#if defined(EMBB_PLATFORM_COMPILER_GNUC)
```

In order to add native support for PowerPC (w/o using C/C++11), you would need to 

1. adapt the CMake files to provide the corresponding define (e.g., EMBB_PLATFORM_ARCH_PPC),
2. add the assembly implementations to the files in the above directory (the part inside `__asm__ __volatile__` largely ignoring the preceding "macro hell").

A good summary for implementing atomic operations can be found here: https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html (more details: http://www.cl.cam.ac.uk/~pes20/papers/topics.html#Power_and_ARM).

Please don't hesitate to contact us if you have any further questions or you need additional information. Contributions are very welcome ;-) If you plan to do the port, we could also provide a template or the like.

**Comment by DannyBoyKN** [comment]
For the moment we'll stay building with the USE_C11_AND_CXX11=ON option and using gcc 4.9.2.
But in order to be able to use 'older' compilers we'll try to make the necessary adaptations for ppc support. But this won't be done that soon. We'll inform you when that will be the case.

Btw.: concerning the failed network plugin tests: it turned out, that the loopback device was not (at all) correctly set up. Now it's done and re-excuting the tests succeeds as well.

Many thanks for your explanations.
